# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn test
    - name: Run Jacoco Coverage
      run: mvn jacoco:report
    - name: Codecov upload
      uses: codecov/codecov-action@v1.5.2
      with:
        token: '0bd9305f-5937-4e62-841c-3c643aba62bb'
        verbose: true
